name: ProxyKeyApp

options:
  bundleIdPrefix: com.kayquenovais

targets:
  ProxyKeyApp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - ContentView.swift
      - ProxyKeyApp.swift
    info:
      path: Info.plist
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.kayquenovais.ProxyKeyApp
      SWIFT_VERSION: 5.0
