name: Testar projeto iOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Instalar XcodeGen
        run: brew install xcodegen

      - name: Gerar projeto Xcode
        run: xcodegen generate

      - name: Compilar
        run: |
          xcodebuild \
            -project ProxyKeyApp.xcodeproj \
            -scheme ProxyKeyApp \
            -sdk iphonesimulator \
            -configuration Debug \
            CODE_SIGNING_ALLOWED=NO \
            build
